import { Bookmark } from "./types";

export const mockBookmarks: Bookmark[] = [
  {
    id: "bm-001",
    author: "@karpathy",
    text: "Just released a new video on tokenization in LLMs. This is probably the most underrated topic in AI right now. Tokenization affects everything from model performance to multilingual capabilities.",
    summary: "Andrej Karpathy's deep dive into LLM tokenization — covers BPE, SentencePiece, and why tokenization choices have cascading effects on model behavior and performance.",
    category: "ai-thoughts",
    bookmarkedAt: "2026-02-08T10:30:00Z",
    url: "https://youtube.com/watch?v=example1",
  },
  {
    id: "bm-002",
    author: "@levelsio",
    text: "I made $2.4M last month from 7 startups running on a single VPS. No employees. Just vibes and PHP.",
    summary: "Pieter Levels shares monthly revenue update across his portfolio of solo projects including PhotoAI, NomadList, and RemoteOK.",
    category: "business",
    bookmarkedAt: "2026-02-15T08:00:00Z",
  },
  {
    id: "bm-003",
    author: "@raaborahat",
    text: "Thread: 10 AI tools that actually save me time every day (not just demos)\n\n1. Cursor for coding\n2. Granola for meeting notes\n3. Arc for browsing\n4. Raycast for everything else...",
    summary: "Curated list of practical AI tools for daily productivity — focuses on tools with real workflow integration rather than novelty demos.",
    category: "ai-tools",
    bookmarkedAt: "2026-01-20T14:00:00Z",
    url: "https://twitter.com/raaborahat/status/example",
  },
  {
    id: "bm-004",
    author: "@shreyasprakash",
    text: "The best onboarding I've ever seen: Linear. Here's a breakdown of why it works so well (thread):\n\n- Progressive disclosure\n- Keyboard-first UX\n- Workspace templates\n- Zero unnecessary steps",
    summary: "Design teardown of Linear's onboarding flow highlighting progressive disclosure, keyboard shortcuts education, and template-driven setup as key patterns.",
    category: "design",
    bookmarkedAt: "2026-02-01T16:30:00Z",
  },
  {
    id: "bm-005",
    author: "@simonw",
    text: "New blog post: Building a CLI tool with Claude that actually works. The trick is structured output + tool use, not just chat completion.",
    summary: "Simon Willison's guide to building reliable CLI tools with LLMs — emphasizes structured output and tool-use patterns over raw text generation.",
    category: "ai-tools",
    bookmarkedAt: "2026-02-10T11:00:00Z",
    url: "https://simonwillison.net/2026/example",
  },
  {
    id: "bm-006",
    author: "@danabramov",
    text: "React Server Components aren't about performance. They're about composition. Once you see them as a way to compose server and client code, everything clicks.",
    summary: "Dan Abramov reframes RSC mental model — the key insight is composition of server/client boundaries, not SSR performance gains.",
    category: "dev-tools",
    bookmarkedAt: "2026-01-28T09:15:00Z",
  },
  {
    id: "bm-007",
    author: "@emilkowalski_",
    text: "I spent 2 weeks perfecting this animation library. It's 2kb gzipped, works with any framework, and the API is just 3 functions. Check it out:",
    summary: "New lightweight animation library (2kb) with a minimal 3-function API. Framework-agnostic with spring physics and gesture support.",
    category: "dev-tools",
    bookmarkedAt: "2026-02-12T17:45:00Z",
    url: "https://github.com/emilkowalski/example",
  },
  {
    id: "bm-008",
    author: "@modal_labs",
    text: "You can now run any Docker container on Modal with a single line of code. GPU included. No infra management. Just `modal run docker://nvidia/cuda`",
    summary: "Modal adds Docker container support — run any container image serverlessly with GPU access. Eliminates infrastructure setup for ML workloads.",
    category: "to-try",
    bookmarkedAt: "2026-02-18T13:00:00Z",
    url: "https://modal.com/blog/docker-support",
  },
  {
    id: "bm-009",
    author: "@benedictevans",
    text: "Long piece on why AI regulation proposals keep missing the point. The problem isn't 'AI safety' in the abstract — it's specific harms in specific domains. You regulate radiology AI differently from ad targeting AI.",
    summary: "Benedict Evans argues AI regulation should be domain-specific rather than technology-specific. Draws parallels to how we regulate cars vs planes vs boats differently.",
    category: "ai-thoughts",
    bookmarkedAt: "2026-01-15T20:00:00Z",
    url: "https://ben-evans.com/2026/example",
  },
  {
    id: "bm-010",
    author: "@jsngr",
    text: "My design system setup for 2026:\n- Figma variables (not tokens)\n- Tailwind v4 theme\n- Radix primitives\n- Framer Motion\n\nThis combo hits different. Everything just works together now.",
    summary: "Modern design system stack recommendation: Figma variables, Tailwind v4, Radix UI, and Framer Motion. Focus on native integration between tools.",
    category: "design",
    bookmarkedAt: "2026-02-05T12:00:00Z",
  },
  {
    id: "bm-011",
    author: "@swyx",
    text: "The AI Engineer stack is converging: TypeScript + Vercel AI SDK + tool use + streaming. If you're not building with this stack yet you're going to have a bad time.",
    summary: "Swyx identifies the emerging standard stack for AI engineering — TypeScript, Vercel AI SDK, tool use patterns, and streaming as the core primitives.",
    category: "ai-tools",
    bookmarkedAt: "2026-02-14T15:30:00Z",
  },
  {
    id: "bm-012",
    author: "@paborenstein",
    text: "Spent 6 months building a SaaS. Made $400. Spent 2 weeks building a simple tool for myself. Other people wanted it. Now it makes $12k/mo. Lesson: scratch your own itch.",
    summary: "Indie hacker journey from failed SaaS to successful tool — validates the 'scratch your own itch' approach to product development.",
    category: "business",
    bookmarkedAt: "2026-01-22T18:00:00Z",
  },
  {
    id: "bm-013",
    author: "@rauchg",
    text: "v0 just got a huge upgrade: it can now generate full Next.js apps with routing, data fetching, and auth. The generated code actually follows best practices.",
    summary: "Vercel's v0 AI tool upgraded to generate complete Next.js applications with proper routing, data fetching patterns, and authentication scaffolding.",
    category: "ai-tools",
    bookmarkedAt: "2026-02-17T10:00:00Z",
    url: "https://v0.dev/changelog",
  },
  {
    id: "bm-014",
    author: "@tldraw",
    text: "We just open-sourced our canvas engine. It handles 100k+ shapes at 60fps, has built-in multiplayer, and the API surface is tiny. Build your own Figma:",
    summary: "tldraw open-sources high-performance canvas engine — handles 100k+ shapes, includes multiplayer support, with a minimal API for building custom design tools.",
    category: "to-try",
    bookmarkedAt: "2026-02-03T14:20:00Z",
    url: "https://github.com/tldraw/tldraw",
  },
  {
    id: "bm-015",
    author: "@waborafield",
    text: "Hot take: the best AI product isn't a chatbot. It's an invisible system that makes your existing tools 10x better. Nobody wants another chat window.",
    summary: "Argument for ambient AI integration over chatbot interfaces — the most impactful AI products enhance existing workflows invisibly rather than adding new interaction surfaces.",
    category: "ai-thoughts",
    bookmarkedAt: "2026-02-09T22:00:00Z",
  },
];
